# Generated by Django 2.2.4 on 2021-03-05 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20210305_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='a_avther',
        ),
        migrations.RemoveField(
            model_name='homeowner',
            name='avther',
        ),
        migrations.AlterField(
            model_name='complaints',
            name='c_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 15, 37, 14, 38876)),
        ),
        migrations.AlterField(
            model_name='guest',
            name='g_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 15, 37, 14, 39527)),
        ),
        migrations.AlterField(
            model_name='public',
            name='p_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 15, 37, 14, 37849)),
        ),
        migrations.AlterField(
            model_name='repair',
            name='r_phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='repair',
            name='r_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 15, 37, 14, 38370)),
        ),
    ]
