# Generated by Django 2.2.4 on 2021-03-05 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_auto_20210305_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='c_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 15, 40, 25, 831556)),
        ),
        migrations.AlterField(
            model_name='guest',
            name='g_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 15, 40, 25, 831916)),
        ),
        migrations.AlterField(
            model_name='public',
            name='p_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 15, 40, 25, 830999)),
        ),
        migrations.AlterField(
            model_name='repair',
            name='r_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 15, 40, 25, 831277)),
        ),
    ]
