# Generated by Django 2.2.4 on 2021-03-05 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_auto_20210305_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='c_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 15, 40, 31, 464137)),
        ),
        migrations.AlterField(
            model_name='guest',
            name='g_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 15, 40, 31, 464488)),
        ),
        migrations.AlterField(
            model_name='public',
            name='p_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 15, 40, 31, 463585)),
        ),
        migrations.AlterField(
            model_name='repair',
            name='r_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 15, 40, 31, 463864)),
        ),
    ]
