# Generated by Django 2.2.4 on 2021-03-06 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_auto_20210305_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeowner',
            name='s_avther',
            field=models.CharField(default='/static/images/default.png', max_length=2048),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='c_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 4, 51, 2, 392791)),
        ),
        migrations.AlterField(
            model_name='guest',
            name='g_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 4, 51, 2, 393161)),
        ),
        migrations.AlterField(
            model_name='public',
            name='p_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 4, 51, 2, 392146)),
        ),
        migrations.AlterField(
            model_name='repair',
            name='r_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 4, 51, 2, 392512)),
        ),
    ]
