# Generated by Django 2.2.11 on 2021-11-24 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=50)),
                ('discipline', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('athlete', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.EventModel')),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.GameModel')),
            ],
        ),
    ]
