# Generated by Django 2.2.11 on 2021-11-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medals',
            name='medal',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='event',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
