# Generated by Django 2.2 on 2021-03-08 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20210308_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='feedback',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(default='未处理', max_length=64),
        ),
        migrations.AddField(
            model_name='report',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 17, 10, 4, 404163)),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='c_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 17, 10, 4, 402171)),
        ),
        migrations.AlterField(
            model_name='guest',
            name='g_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 17, 10, 4, 403168)),
        ),
        migrations.AlterField(
            model_name='public',
            name='p_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 17, 10, 4, 402171)),
        ),
        migrations.AlterField(
            model_name='repair',
            name='r_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 17, 10, 4, 402171)),
        ),
    ]
