# Generated by Django 2.2 on 2021-03-05 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_complaints_guest_public_repair_report_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='c_status',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='c_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 17, 44, 22, 307352)),
        ),
        migrations.AlterField(
            model_name='guest',
            name='g_status',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='guest',
            name='g_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 17, 44, 22, 308349)),
        ),
        migrations.AlterField(
            model_name='public',
            name='p_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 17, 44, 22, 305359)),
        ),
        migrations.AlterField(
            model_name='repair',
            name='r_name',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='repair',
            name='r_status',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='repair',
            name='r_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 17, 44, 22, 306355)),
        ),
    ]
