# Generated by Django 2.2.4 on 2021-04-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20210414_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='title',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='file',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='video',
            name='pic',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.CharField(max_length=2048),
        ),
    ]
