# Generated by Django 2.2.4 on 2021-04-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20210414_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='replay',
            field=models.TextField(null=True),
        ),
    ]
