# Generated by Django 2.2.4 on 2021-04-20 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_auto_20210414_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='replay',
        ),
        migrations.RemoveField(
            model_name='message',
            name='replay_time',
        ),
        migrations.CreateModel(
            name='Message2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replay', models.TextField(null=True)),
                ('replay_time', models.DateTimeField(null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
