# Generated by Django 2.2.11 on 2021-11-16 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=2048)),
                ('phone', models.CharField(max_length=2048)),
                ('address', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类别名')),
            ],
        ),
        migrations.CreateModel(
            name='CollectGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, verbose_name='标题')),
                ('size', models.CharField(max_length=64, verbose_name='规格')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('stock', models.IntegerField(verbose_name='库存')),
                ('sold', models.IntegerField(blank=True, default=0, null=True, verbose_name='已售')),
                ('publish_date', models.DateField(verbose_name='发布时间')),
                ('goods_image', models.ImageField(upload_to='static/image', verbose_name='商品主图')),
                ('goods_detail_iamge', models.ImageField(upload_to='static/image', verbose_name='商品细节图片')),
                ('content', models.TextField(verbose_name='文字描述')),
                ('collect', models.IntegerField(blank=True, default=0, null=True, verbose_name='收藏')),
                ('expressFee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='配送费')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Address')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num', models.IntegerField(default=1)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Order')),
            ],
        ),
    ]
