# Generated by Django 2.2 on 2021-03-18 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20210318_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='num',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='goods',
            name='collect',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='收藏'),
        ),
        migrations.AlterField(
            model_name='message',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 18, 13, 46, 51, 407405)),
        ),
    ]
