# Generated by Django 2.2 on 2021-03-08 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='a_phone',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='c_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 17, 5, 9, 276649)),
        ),
        migrations.AlterField(
            model_name='guest',
            name='g_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 17, 5, 9, 277645)),
        ),
        migrations.AlterField(
            model_name='homeowner',
            name='h_cphone',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='homeowner',
            name='h_phone',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='public',
            name='p_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 17, 5, 9, 275627)),
        ),
        migrations.AlterField(
            model_name='repair',
            name='r_phone',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='repair',
            name='r_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 17, 5, 9, 276649)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='s_cname',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='staff',
            name='s_cphone',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='staff',
            name='s_phone',
            field=models.CharField(max_length=64),
        ),
    ]
