# Generated by Django 3.2.8 on 2021-11-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_user_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birtday',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
