# Generated by Django 3.2.8 on 2021-11-28 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20211128_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmodel',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myApp.coursedetail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursestudent',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.coursedetail'),
        ),
    ]
