# Generated by Django 3.2.8 on 2021-11-28 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_auto_20211128_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='course',
        ),
        migrations.AddField(
            model_name='theme',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myApp.user'),
            preserve_default=False,
        ),
    ]
