# Generated by Django 3.2.8 on 2021-11-28 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_auto_20211128_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmodel',
            name='type',
        ),
        migrations.RemoveField(
            model_name='groupmodel',
            name='user',
        ),
        migrations.CreateModel(
            name='GroupStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.groupmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
