# Generated by Django 3.2.8 on 2021-11-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_auto_20211128_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstudent',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
