# Generated by Django 3.2.8 on 2021-11-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_groupstudent_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='createDate',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='summary',
        ),
    ]
